### ISSUE TITLE
using module error

### ISSUE THREAD

**Issue by mafzalzadeh** [openmeetings/openmeetings-moodle-plugin#30]
Hi.

When I want add an openmeetings action it shows these errors:

    line 35 of \mod\openmeetings\api\OmRestService.php: ArgumentCountError thrown
    line 82 of \mod\openmeetings\api\OmGateway.php: call to OmRestService->__construct()
    line 52 of \mod\openmeetings\mod_form.php: call to OmGateway->login()
    line 135 of \course\modedit.php: call to require_once()

Thanks.

**Comment by solomax** [comment]
What version of Moodle are you using?
What version of Moodle plugin are you using?
What version of PHP do you have?

**Comment by mafzalzadeh** [comment]
Moodle 3.5.2
Moodle plugin  Release 3.0.0.6
PHP Version 7.1.10

Thanks

**Comment by solomax** [comment]
Just have tested with:

Moodle 3.5.2
OM plugin 3.0.0.6
PHP 7.0.32 (under Ubuntu 16)

Everything seems to work
What OS do you have?

**Comment by mafzalzadeh** [comment]
I'm Testing on windows10 with xampp.
If need to change OS or anything I can do it.

thanks

**Comment by solomax** [comment]
I have tested under Apache Web Server so far .... 
there also was nginx installation some time ago

Will try to set up VM with Win10 and xampp, not sure how long it will take :(

**Comment by mafzalzadeh** [comment]
Ok.
I'll test it under a linux VM and tell you the result.
thanks

**Comment by mafzalzadeh** [comment]
No Problem for wating.
I'll also try to do that and will tell you the result
Thanks.

**Comment by solomax** [comment]
Reproducible using XAMPP+PHP 7.1 on Win10
Will see what I can do

Thanks for the report

**Comment by solomax** [comment]
Should be fixed, next version will be released right after 4.0.6

**Comment by mafzalzadeh** [comment]
after the changes I still have problem with connecting:

Exception - Too few arguments to function OmRestService::__construct(), 0 passed in [dirroot]\mod\openmeetings\api\OmGateway.php on line 78 and exactly 1 expected

**Comment by solomax** [comment]
here is the line #78: https://github.com/openmeetings/openmeetings-moodle-plugin/blob/master/api/OmGateway.php#L78
there is no OmRestService call ...

How have you applied changes to your server?

**Comment by mafzalzadeh** [comment]
I just copied and replaced all of the new version files from the git.

**Comment by solomax** [comment]
I'm afraid it might not work this way :(
You need to clone git repo and run `ant` in cloned folder
then replace `moodle/mod/openmeetings` folder contents with contents of `dist` folder created by build script

**Comment by mafzalzadeh** [comment]
OK. Thanks. I'll do it and tell you the result.

**Comment by mafzalzadeh** [comment]
@solomax 
The problem solved.
Thanks.

**Comment by solomax** [comment]
Great!
Thanks for report and for checking
Plugin will be released next week
